### ISSUE TITLE
windows 7: lack of dll 

### ISSUE THREAD

**Issue by eeric** [zetane/viewer#11]
api-ms-win-core-processtopology-obsolete-l1-1-0.dll

**Comment by konafah** [comment]
Hi. We are ending support for Windows 7 in our upcoming release as [Windows 7 no longer supported by Microsoft.](https://www.microsoft.com/en-ca/windows/windows-7-end-of-life-support-information).

In the meantime, to obtain CRT dlls for Windows 7, please try:
* [Windows 10 Universal C Runtime](https://www.microsoft.com/en-us/download/details.aspx?id=48234)
* [Visual C++ Redistributable package for Visual Studio 2015-2022](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022)
