### ISSUE TITLE
Cannot use pro version after paying

### ISSUE THREAD

**Issue by ThomasMouse** [zetane/viewer#12]
![2022-02-17 17-35-54屏幕截图](https://user-images.githubusercontent.com/73480935/154471808-e5defaac-3fdf-4411-809b-f3b1a1bce393.png)
I cannot use the pro version after I pay for it.
Operating System: Ubuntu 20.04

**Comment by ThomasMouse** [comment]
![2022-02-17 19-28-14屏幕截图](https://user-images.githubusercontent.com/73480935/154472711-60a6fe0f-a123-4cfc-b809-1883c164cfe6.png)

**Comment by konafah** [comment]
Hi. Thank you for reaching out about this issue. We've restored access to the account and emailed you directly with more details.

If you need any further assistance please don't hesitate to email us back or join our slack support channel (https://zetane.com/join-slack).
