### ISSUE TITLE
Free Trial not Available

### ISSUE THREAD

**Issue by Whadup** [zetane/viewer#4]
After clicking "upgrade 2 pro", I arrive at your pricing page. Clicking on "free trial" redirects me to the documentation, which instructs me to click the button "upgrade 2 pro". Now I'm stuck in an infinite loop and unhappy about it.

I'd like to successfully exit this loop and try your product. Any Tips?

**Comment by jmagoon** [comment]
Version 1.5.0 (released today) allows you to use what was our old 30 day trial for free, with a certain amount of model runs per day for a free user. Let us know if you have any issues or if it works for you.

**Comment by Whadup** [comment]
I'm running todays version, but the python API still prompts the request that I upgrade to pro in the viewer while my python code hangs indefinitely.

**Comment by jmagoon** [comment]
Looks like your license had an incorrect permission set, it should be working now.
