### ISSUE TITLE
How to generate the corresponding model format?

### ISSUE THREAD

**Issue by Harr7y** [zetane/viewer#9]
A usual saved format for Pytorch is '.pth'， how could we generate the own ZTN or ONNX format self-designed models with Pytorch.

**Comment by amansingh0330** [comment]
@Harr7y for pth models if you load it in python (generally you need model definition for pth models) then torch supports the onnx conversion implicitly 

which is something like this 
`torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)`

after converting to onnx you can easily convert it to ztn following the zetane documentation

**Comment by Harr7y** [comment]
> @Harr7y for pth models if you load it in python (generally you need model definition for pth models) then torch supports the onnx conversion implicitly
> 
> which is something like this `torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)`
> 
> after converting to onnx you can easily convert it to ztn following the zetane documentation

Thanks a lot for your reply.
